const MEANINGS = {
  15: "fifteen",
  Aber: "but",
  Also: "so",
  Es: "it",
  Fall: ["case", "fall"],
  Fortschritte: "progress",
  Ja: "yes",
  Levels: "levels",
  Menge: "amount",
  Minuten: "minutes",
  Sätze: "sentences",
  Spaß: ["fun", "enjoyment"],
  Sprache: ["language", "speech"],
  Sprachen: "languages",
  Tag: "day",
  Tipps: "tips",
  Verfügung: "disposal",
  Wenn: "if",
  Wochenplan: "weekly schedule",
  Zeit: ["time", "era", "period"],
  allen: "all",
  auch: "also",
  aufwenden: "spend",
  aus: "from",
  beachten: "keep in mind",
  aber: "but",
  da: "there",
  dann: "then",
  dahingehend: "in that regard",
  das: "that",
  dass: "that",
  davon: "of that",
  dein: "your",
  den: "the",
  der: "the",
  die: "the",
  dir: "you",
  du: "you",
  eine: "a",
  ein: "a",
  erst: "first",
  erste: "first",
  erreichen: "reach",
  es: "it",
  für: "for",
  ganze: "whole",
  gar: "at all",
  gehen: "go",
  gleichzeitig: "at the same time",
  gut: ["good", "well"],
  gute: "good",
  hast: "have",
  ich: "I",
  in: "in",
  irgendwie: "somehow",
  ist: "is",
  ja: "yes",
  je: "per",
  jeden: "every",
  jetzt: ["now", "currently"],
  keiner: "no",
  kommen: ["come", "arrive"],
  kannst: "can",
  lernen: ["learn", "study"],
  lernst: "learn",
  macht: "makes",
  machen: ["do", "make"],
  machst: "make",
  mal: "time",
  man: "one",
  maximal: "at most",
  mehrere: "several",
  mehreren: "several",
  meine: "my",
  mit: "with",
  möglich: "possible",
  muss: "must",
  musst: "have to",
  möchtest: "would like",
  nachdem: "after",
  natürlich: "of course",
  nicht: "not",
  nur: "only",
  paar: "a few",
  sagen: ["say", "tell", "mean"],
  sind: "are",
  sowieso: "anyway",
  um: "in order to",
  und: "and",
  vielleicht: "maybe",
  voll: ["full", "busy"],
  vorhast: "intend",
  wahrscheinlich: "probably",
  weit: ["far", "a long way"],
  wenn: "if",
  wie: "how",
  willst: "want",
  wirklich: "really",
  wir: "we",
  wirst: "will",
  zehn: "ten",
  zu: "to",
  zur: "to the",
  würde: "would",
};

export function meaningsFor(word) {
  const entry = MEANINGS[word];
  if (!entry) return [word];
  return Array.isArray(entry) ? entry : [entry];
}

export function formatMeanings(word) {
  return meaningsFor(word).join(" ; ");
}
